# general
seed: 1
device: 'cuda'
output_path: 'tokenflow_intermediate'

# data
data_path: '/home/sungwoo/TokenFlow/data/DAVIS/JPEGImages/480p/monkeys'
latents_path: '/home/sungwoo/TokenFlow/data/preprocessing' # should be the same as 'save_dir' arg used in preprocess
n_inversion_steps: 500 # for retrieving the latents of the inversion
n_frames: 40

# diffusion
sd_version: '2.1'
guidance_scale: 7.5
n_timesteps: 50
prompt: "two brown bears on ice"
negative_prompt: "ugly, blurry, low res, unrealistic, unaesthetic"
batch_size: 8

# pnp params -- injection thresholds ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
deflicker_timesteps: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]